from django.shortcuts import render
from django.http import JsonResponse
import PyPDF2
from langchain.embeddings import SentenceTransformerEmbeddings
from langchain.vectorstores import FAISS
import requests
import os
from embeding_model import faiss_emergency, faiss_general


# Mistral API query function (Using API key)
def query_mistral(prompt, context, history=None):
    # Build conversation history string
    history_str = ""
    if history:
        for h in history:
            history_str += f"User: {h['user']}\nAssistant: {h['bot']}\n"
    history_str += f"User: {prompt}\n"

    full_prompt = (
        "You are a polite, helpful assistant. "
        "For greetings, goodbyes, and general conversation, answer naturally using your general knowledge. "
        "For all other questions, use the information provided below if relevant. "
        "If you do not know the answer, reply exactly: 'Sorry, the answer is not available.'\n\n"
        "Do not mention the provided document or its contents directly.\n\n"
        f"{context}\n\n"
        f"Conversation history:\n{history_str}"
    )

    api_url = "https://api.mistral.ai/v1/chat/completions"
    api_key = "vu8IU45HuPcULXqiUY0OcpbXCUc1LZyH" 
                
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "mistral-tiny",
        "messages": [
            {"role": "user", "content": full_prompt}
        ],
        "temperature": 0.2
    }

    try:
        response = requests.post(api_url, headers=headers, json=payload)
        response.raise_for_status()
        answer = response.json()["choices"][0]["message"]["content"].strip()
        return answer
    except Exception as e:
        print("Error communicating with Mistral API:", e)
        return "Sorry, I could not get a response from the chatbot server."

def find_relevant_chunks(user_input, chatbot_type, top_k=3):
    """
    Finds relevant chunks using semantic search with embeddings.
    
    Args:
        user_input (str): The user's query.
        chatbot_type (str): 'emergency' or 'general'.
        top_k (int): Number of top similar chunks to return.

    Returns:
        List of relevant text chunks.
    """
    # Select the appropriate FAISS index
    if chatbot_type == 'emergency':
        faiss_index = faiss_emergency
    else:
        faiss_index = faiss_general

    # Perform semantic similarity search
    relevant_docs = faiss_index.similarity_search(user_input, k=top_k)

    # Extract text chunks from the search results
    relevant_chunks = [doc.page_content for doc in relevant_docs]

    return relevant_chunks

# 2. View to Render the Chatbot UI
def chatbot_home(request):
    return render(request, 'chatbot.html')

# 3. View to Handle Chatbot Input
def get_chatbot_response(request):
    if request.method == 'GET':
        user_input = request.GET.get('user_input', '').strip()
        source = request.GET.get('source', 'general').lower()
        print("DEBUG: Source received from frontend:", source)

        general_keywords = [
            "hello", "hi", "hey", "good morning", "good afternoon", "good evening",
            "how are you", "what's up", "goodbye", "bye", "see you", "thank you", "thanks"
        ]

        assistant_type = source

        # Check if user input is a general conversation
        if any(greet in user_input.lower() for greet in general_keywords):
            context = f"(You are a {assistant_type} safety assistant.)"
            print(f"DEBUG: General conversation detected. Assistant type: {assistant_type}")
            bot_response = query_mistral(user_input, context, [])
            print(f"DEBUG: Response generated by Mistral for general conversation. Assistant type: {assistant_type}")
            bot_response += f"\n\n[DEBUG: General conversation | Source={assistant_type}]"
        else:
            # Use the new function to find relevant chunks
            relevant_chunks = find_relevant_chunks(user_input, assistant_type)

            # If relevant chunks found, use them as context
            if relevant_chunks:
                context = " ".join(relevant_chunks[:2])
                print(f"DEBUG: Using context for Mistral: {context}")
                history = request.session.get('chat_history', [])
                history = history[-5:]
                bot_response = query_mistral(user_input, context, history)
                print(f"DEBUG: Response generated by Mistral from {assistant_type} PDF context.")
                bot_response += f"\n\n[DEBUG: PDF context | Source={assistant_type}]"

                print("DEBUG: Relevant chunks found:")
                print(relevant_chunks[:2])
            # If no relevant chunks found, send apology 
            else:
                print(f"DEBUG: No relevant info found in {assistant_type} PDF. Sending apology.")
                bot_response = (
                    "Sorry, I couldn't find an answer to your question. Please try rephrasing your question or ask something else."
                    f"\n\n[DEBUG: No relevant chunk | Source={assistant_type}]"
                )

        # Update conversation history in session
        history = request.session.get('chat_history', [])
        history.append({'user': user_input, 'bot': bot_response})
        request.session['chat_history'] = history

        print(f"DEBUG: Final response sent to frontend: {bot_response[:100]}...")  # Print first 100 chars
        return JsonResponse({'response': bot_response})



